use super::client::{self, ChatMessage};

/// Starts a fresh conversation with the given (already-composed) system
/// prompt — normally the active persona's `compose_system_prompt()`. If
/// `first_message` is non-empty, it's seeded directly as the persona's
/// opening line (not generated by the model) so it's shown to the user
/// immediately and is part of context for everything that follows.
pub fn new_conversation(system_prompt: &str, first_message: &str) -> Vec<ChatMessage> {
    let mut history = vec![ChatMessage::system(system_prompt)];
    if !first_message.trim().is_empty() {
        history.push(ChatMessage::assistant(first_message.to_string()));
    }
    history
}

/// Appends the user's message to history, streams the assistant's reply
/// (invoking `on_delta` per chunk), appends the reply to history, and
/// returns the full reply text.
pub async fn run_chat_turn(
    port: u16,
    history: &mut Vec<ChatMessage>,
    user_message: String,
    on_delta: impl FnMut(&str),
) -> anyhow::Result<String> {
    history.push(ChatMessage::user(user_message));

    let reply = client::stream_chat(port, history, on_delta).await?;

    history.push(ChatMessage::assistant(reply.clone()));

    Ok(reply)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Settings;
    use crate::llm::process::LlmProcess;
    use std::path::PathBuf;

    /// Not a CI test — exercises a real chat turn against a real
    /// llama-server + model to manually verify plain chat works, with no
    /// tool-calling involved at all.
    /// Run with: cargo test --lib -- --ignored --nocapture plain_chat_round_trip
    #[ignore]
    #[tokio::test]
    async fn plain_chat_round_trip() {
        let settings = Settings {
            llama_server_path: Some(PathBuf::from(
                "/home/erik/llama.cpp/build/bin/llama-server",
            )),
            model_path: Some(PathBuf::from(
                "/home/erik/models/qwen2.5-1.5b-instruct-q4_k_m.gguf",
            )),
            port: 8095,
            context_size: 4096,
            active_persona_id: None,
        };

        let mut llm = LlmProcess::default();
        let port = llm
            .ensure_running(&settings)
            .await
            .expect("llama-server should start");

        let mut history = new_conversation("You are Desky, a friendly and concise chatbot.", "");

        let reply = run_chat_turn(
            port,
            &mut history,
            "Say hello in exactly three words.".to_string(),
            |_delta| {},
        )
        .await
        .expect("chat turn should succeed");

        println!("=== MODEL REPLY ===\n{reply}\n===================");
        assert!(!reply.trim().is_empty());

        llm.shutdown().await;
    }
}
